language: cpp
sudo: required
services:
    - docker

before_install:
    - docker pull skarlso/gcc

script:
    - docker run --rm -e TRAVIS_JOB_ID=${TRAVIS_JOB_ID} -v $(pwd):/data -w /data skarlso/gcc /bin/bash -lc "cd build && cmake .. && cmake --build . && ctest"
