# Environment Setup
language: cpp
dist: trusty
addons:
  apt:
    sources:
      - boost-latest
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - libboost1.55-all-dev
      - openssl
      - gcc-6
      - g++-6

# Build Steps
script:
    - cd build
    - cmake .. && cmake --build . && ctest
