# Environment Setup
language: cpp
dist: trusty
# To get the latest cmake
addons:
  apt:
    sources:
    #   - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - boost-latest
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    #   - ubuntu-toolchain-r-test
    packages:
      - libboost1.55-all-dev
      - openssl
    #   - cmake
    #   - cmake-data
      - gcc-6
      - g++-6
    #   - clang
    #   - libc++-dev

# Build Steps
script:
    - cd build
    - cmake .. && cmake --build . && ctest
