# Environment Setup
language: cpp

# To get the latest cmake
addons:
  apt:
    sources:
    #   - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libboost1.55-all-dev
      - cmake
      - cmake-data
      - gcc-4.9
      - g++-4.9
      - clang
      - libc++-dev

# Build Steps
script:
    - cd build
    - cmake .. && cmake --build . && ctest
